server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/raovat
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635296556A581E3272357538782F713F0428475B4B6250635367563B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

apiContactEmail: ""
apiContactName: ""
apiContactUrl: ""
apiDescription: ""
apiTitle: "Web Rao Vat"
apiVersion: "1.0.0"