name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: "dev"
          heroku_api_key:  ${{ secrets.API_KEY }}
          heroku_app_name: "ec-api"
          heroku_email:  ${{ secrets.EMAIL }}
          args: --skip-database-initialization
